/**
 * File Scanner Module
 *
 * @author 686f6c61
 * @repository https://github.com/686f6c61/hardcoded-api-key-detector
 * @license MIT
 *
 * Scans files and directories for hardcoded API keys
 */

const fs = require('fs-extra');
const path = require('path');
const { glob } = require('glob');

const DEFAULT_EXCLUDE = [
  'node_modules/**',
  '.git/**',
  'dist/**',
  'build/**',
  'coverage/**',
  '*.min.js',
  '*.min.css',
  'package-lock.json',
  'yarn.lock'
];

const DEFAULT_INCLUDE = [
  '**/*.js',
  '**/*.ts',
  '**/*.jsx',
  '**/*.tsx',
  '**/*.json',
  '**/*.yml',
  '**/*.yaml',
  '**/*.env*',
  '**/*.config.js',
  '**/*.config.ts',
  '**/*.py',
  '**/*.php',
  '**/*.rb',
  '**/*.go',
  '**/*.java',
  '**/*.cpp',
  '**/*.c',
  '**/*.h',
  '**/*.sh',
  '**/*.bash',
  '**/*.zsh',
  '**/*.ps1',
  '**/*.dockerfile',
  '**/Dockerfile*',
  '**/*.tf',
  '**/*.tfvars'
];

/**
 * Scans directory for files matching include patterns
 *
 * @param {string} directory - Directory to scan
 * @param {string[]} exclude - Additional exclude patterns
 * @returns {Promise<string[]>} Array of absolute file paths
 */
async function scanFiles(directory, exclude = []) {
  const excludePatterns = [...DEFAULT_EXCLUDE, ...exclude];

  const files = [];
  for (const pattern of DEFAULT_INCLUDE) {
    const matches = await glob(pattern, {
      cwd: directory,
      ignore: excludePatterns,
      absolute: true,
      nodir: true
    });
    files.push(...matches);
  }

  return [...new Set(files)]; // Remove duplicates
}

/**
 * Initializes configuration file
 *
 * @returns {Promise<boolean>} Success status
 */
async function initConfig() {
  const configPath = path.join(process.cwd(), '.hardcoded-detector.json');

  if (await fs.pathExists(configPath)) {
    console.log('[WARNING] Configuration file already exists');
    return false;
  }

  const defaultConfig = {
    version: '1.0.0',
    exclude: [
      'test/**',
      'tests/**',
      'spec/**',
      'mocks/**',
      '*.test.js',
      '*.spec.js'
    ],
    severity: 'medium',
    output: {
      format: 'console',
      file: null
    },
    hooks: {
      preCommit: true,
      prePush: false
    },
    patterns: {
      custom: [],
      disabled: []
    }
  };

  await fs.writeJSON(configPath, defaultConfig, { spaces: 2 });
  console.log('[SUCCESS] Configuration file created: .hardcoded-detector.json');
  return true;
}

/**
 * Installs git pre-commit hook
 *
 * @returns {Promise<boolean>} Success status
 */
async function installHooks() {
  const gitDir = path.join(process.cwd(), '.git');

  if (!(await fs.pathExists(gitDir))) {
    console.log('[ERROR] Not a git repository');
    return false;
  }

  const hooksDir = path.join(gitDir, 'hooks');
  await fs.ensureDir(hooksDir);

  const preCommitHook = `#!/bin/sh
# Hardcoded API Detector Pre-commit Hook
# Generated by hardcoded-api-detector

npx hardcoded-api-detector scan --staged

if [ $? -ne 0 ]; then
    echo "[ERROR] Hardcoded API keys detected! Commit aborted."
    echo "Run 'npx hardcoded-api-detector scan' for details."
    exit 1
fi
`;

  const preCommitPath = path.join(hooksDir, 'pre-commit');
  await fs.writeFile(preCommitPath, preCommitHook);
  await fs.chmod(preCommitPath, '755');

  console.log('[SUCCESS] Git pre-commit hook installed');
  return true;
}

module.exports = {
  scanFiles,
  initConfig,
  installHooks
};
